In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd

# Set the path to the file you'd like to load
file_path = "movies_metadata.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sibamsamanta07/movies-dataset-45k-films-with-budget-and-revenue",
  file_path,
)

df.head()

c:\Users\Pichau\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Pichau\AppData\Local\Temp\ipykernel_1992\3151394085.py:11: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(
c:\Users\Pichau\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\kagglehub\pandas_datasets.py:92: DtypeWarning: Columns (10: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
display(df.shape)
# Quantidade de linhas e colunas
# Quantidade de Nulos
display(df.isnull().sum())
df.drop(columns='homepage')
df.drop(columns = 'imdb_id')

(45466, 24)

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

,adult,belongs_to_collection,budget,genres,homepage,id,original_language,original_title,overview,popularity,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [4]:
# Removendo colunas que não vão impactar na nossa análise e possuem, ou, em sua maior parte, possuem o 'valor' vazio
df = df.drop(columns = ["homepage","belongs_to_collection","tagline",'imdb_id','poster_path','overview'])

# Agora são 6 casos 'engraçados', pois 6 filmes não possuem titulos, como vou avaliar? então decidi remover as linhas sem titulo
df = df.dropna(subset = ['title'])

# Após o tratamento, e depois de pesquisar melhor como tratar os dados, vi que budget, revenue, runtime ... não possuiam NaN. mas isso nao significava que o valor não podia ser 0,
# então, fui ver se existia algum valor 0 nas colunas de valores, que deram preenchidas

print(df[['budget','revenue','runtime','popularity','vote_average','vote_count']].dtypes)

# após a execução percebi que budget e popularity eram 'objects' e não numericos, entao tive que tratar - coerce = transformar valores que não podem
# ser convertidos em NaN, permitindo identificá-los e tratá-los depois.

df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')

print()
print(df[['budget','revenue','runtime','popularity','vote_average','vote_count']].dtypes)

#Check valores iguais a 0
print("\nQuantidade de valores iguais a zero:")

for coluna in [
    "budget",
    "revenue",
    "runtime",
    "popularity",
    "vote_average",
    "vote_count"
]:
    print(coluna, (df[coluna] == 0).sum())

budget              str
revenue         float64
runtime         float64
popularity       object
vote_average    float64
vote_count      float64
dtype: object

budget            int64
revenue         float64
runtime         float64
popularity      float64
vote_average    float64
vote_count      float64
dtype: object

Quantidade de valores iguais a zero:
budget 36570
revenue 38052
runtime 1558
popularity 66
vote_average 2998
vote_count 2899

In [5]:
# Como conseguimos ver, +- 38k filmes, não possuem valores informados, não consiguiriamos fazer uma análise sem esses dados, então decidi remover e utilizar a menor amostra

# Substituindo 0 por NaN
df['budget'] = df['budget'].replace(0, float('nan'))
df['revenue'] = df['revenue'].replace(0, float('nan'))
df['runtime'] = df['runtime'].replace(0, float('nan'))

#Removendo NaN + criando cópia do df só com os dados preenchidos, para preservar o bd
df_filmes_completos = df.dropna(subset=['budget', 'revenue', 'runtime']).copy() # quando quiser analisar so filmes com revenue, budget etc -> df_filmes_completos , caso contrario, somente df

print("Base geral:", df.shape)
print("Base com dados completos:", df_filmes_completos.shape)
#verificando quantos filmes com dados integros sobraram

Base geral: (45460, 18)
Base com dados completos: (5369, 18)

In [6]:
# Verifica quantos registros completamente duplicados
# existem na base, sem realizar nenhuma remoção neste momento.

quantidade_duplicados = df.duplicated().sum()

print("Registros duplicados:", quantidade_duplicados)

Registros duplicados: 17

In [7]:
# Exibe todos os registros que possuem uma cópia duplicada.
# keep=False faz com que tanto o registro original quanto as cópias sejam exibidos

duplicados = df[df.duplicated(keep=False)]

display(duplicados)

,adult,budget,genres,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,title,video,vote_average,vote_count
676,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",105045,de,Das Versprechen,0.122178,"[{'name': 'Studio Babelsberg', 'id': 264}, {'n...","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",1995-02-16,NaN,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,The Promise,False,5.0,1.0
1465,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",105045,de,Das Versprechen,0.122178,"[{'name': 'Studio Babelsberg', 'id': 264}, {'n...","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",1995-02-16,NaN,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,The Promise,False,5.0,1.0
7345,False,NaN,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",5511,fr,Le Samouraï,9.091288,"[{'name': 'Fida cinematografica', 'id': 73}, {...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1967-10-25,39481.0,105.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,Le Samouraï,False,7.9,187.0
8068,False,NaN,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",23305,en,The Warrior,1.967992,"[{'name': 'Filmfour', 'id': 6705}]","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2001-09-23,NaN,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,The Warrior,False,6.3,15.0
9165,False,NaN,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",5511,fr,Le Samouraï,9.091288,"[{'name': 'Fida cinematografica', 'id': 73}, {...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1967-10-25,39481.0,105.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,Le Samouraï,False,7.9,187.0
9327,False,NaN,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",23305,en,The Warrior,1.967992,"[{'name': 'Filmfour', 'id': 6705}]","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2001-09-23,NaN,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,The Warrior,False,6.3,15.0
13220,False,NaN,"[{'id': 99, 'name': 'Documentary'}]",159849,en,Why We Fight: Divide and Conquer,0.473322,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1943-01-01,NaN,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why We Fight: Divide and Conquer,False,5.0,1.0
13261,False,NaN,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",141971,fi,Blackout,0.411949,"[{'name': 'Filmiteollisuus Fine', 'id': 5166}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2008-12-26,NaN,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Blackout,False,6.7,3.0
13375,False,NaN,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",141971,fi,Blackout,0.411949,"[{'name': 'Filmiteollisuus Fine', 'id': 5166}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2008-12-26,NaN,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Blackout,False,6.7,3.0
13603,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",168538,en,Nana,1.276602,"[{'name': 'Cannon Group', 'id': 1444}, {'name'...",[],1983-06-13,NaN,92.0,[],Released,"Nana, the True Key of Pleasure",False,4.7,3.0
13946,False,NaN,"[{'id': 35, 'name': 'Comedy'}]",97995,en,Seven Years Bad Luck,0.141558,"[{'name': 'Max Linder Productions', 'id': 38162}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1921-02-06,NaN,62.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Seven Years Bad Luck,False,5.6,4.0
14000,False,NaN,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",18440,en,Days of Darkness,1.436085,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-01-01,NaN,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Days of Darkness,False,5.0,5.0
14012,False,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",11115,en,Deal,6.880365,"[{'name': 'Andertainment Group', 'id': 2634}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2008-01-29,NaN,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Deal,False,5.2,22.0
15702,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",42495,en,King Lear,0.187901,"[{'name': 'Royal Shakespeare Company', 'id': 5...","[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...",1971-02-04,NaN,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,King Lear,False,8.0,3.0
16167,False,NaN,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",99080,en,The Viking,0.002362,[],[],1931-06-21,NaN,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Viking,False,0.0,0.0
16764,False,NaN,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",141971,fi,Blackout,0.411949,"[{'name': 'Filmiteollisuus Fine', 'id': 5166}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2008-12-26,NaN,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Blackout,False,6.7,3.0
17229,False,NaN,"[{'id': 18, 'name': 'Drama'}]",25541,da,Broderskab,2.587911,[],"[{'iso_3166_1': 'SE', 'name': 'Sweden'}, {'iso...",2009-10-21,NaN,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,Brotherhood,False,7.1,21.0
19890,False,NaN,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",119916,en,The Tempest,0.000018,[],[],1980-02-27,NaN,123.0,[],Released,The Tempest,False,0.0,0.0
19925,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",152795,en,The Congress,8.534039,"[{'name': 'Pandora Filmproduktion', 'id': 254}...","[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2013-05-16,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Congress,False,6.4,165.0
21165,False,NaN,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",119916,en,The Tempest,0.000018,[],[],1980-02-27,NaN,123.0,[],Released,The Tempest,False,0.0,0.0
21854,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",152795,en,The Congress,8.534039,"[{'name': 'Pandora Filmproduktion', 'id': 254}...","[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2013-05-16,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Congress,False,6.4,165.0
22151,False,NaN,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",18440,en,Days of Darkness,1.436085,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-01-01,NaN,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Days of Darkness,False,5.0,5.0
23044,False,NaN,"[{'id': 18, 'name': 'Drama'}]",25541,da,Broderskab,2.587911,[],"[{'iso_3166_1': 'SE', 'name': 'Sweden'}, {'iso...",2009-10-21,NaN,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,Brotherhood,False,7.1,21.0
24164,False,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",265189,sv,Turist,12.165685,"[{'name': 'Motlys', 'id': 2783}, {'name': 'Cop...","[{'iso_3166_1': 'NO', 'name': 'Norway'}, {'iso...",2014-08-15,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,Force Majeure,False,6.8,255.0
24844,False,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",11115,en,Deal,6.880365,"[{'name': 'Andertainment Group', 'id': 2634}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2008-01-29,NaN,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Deal,False,5.2,22.0
28860,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",168538,en,Nana,1.276602,"[{'name': 'Cannon Group', 'id': 1444}, {'name'...",[],1983-06-13,NaN,92.0,[],Released,"Nana, the True Key of Pleasure",False,4.7,3.0
29374,False,NaN,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",42495,en,King Lear,0.187901,"[{'name': 'Royal Shakespeare Company', 'id': 5...","[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...",1971-02-04,NaN,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,King Lear,False,8.0,3.0
33184,False,980000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",298721,th,รักที่ขอนแก่น,2.535419,"[{'name': 'Match Factory, The', 'id': 7306}, {...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-09-02,NaN,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Cemetery of Splendour,False,4.4,50.0
35798,False,NaN,"[{'id': 99, 'name': 'Documentary'}]",159849,en,Why We Fight: Divide and Conquer,0.473322,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1943-01-01,NaN,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why We Fight: Divide and Conquer,False,5.0,1.0
38871,False,NaN,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",99080,en,The Viking,0.002362,[],[],1931-06-21,NaN,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Viking,False,0.0,0.0
40040,False,980000.0,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",298721,th,รักที่ขอนแก่น,2.535419,"[{'name': 'Match Factory, The', 'id': 7306}, {...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-09-02,NaN,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Cemetery of Splendour,False,4.4,50.0
40276,False,NaN,"[{'id': 35, 'name': 'Comedy'}]",97995,en,Seven Years Bad Luck,0.141558,"[{'name': 'Max Linder Productions', 'id': 38162}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1921-02-06,NaN,62.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Seven Years Bad Luck,False,5.6,4.0
45265,False,NaN,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",265189,sv,Turist,12.165685,"[{'name': 'Motlys', 'id': 2783}, {'name': 'Cop...","[{'iso_3166_1': 'NO', 'name': 'Norway'}, {'iso...",2014-08-15,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,Force Majeure,False,6.8,255.0

In [8]:
#Removendo duplicados

df = df.drop_duplicates()

#verificando
print("Duplicados restantes:", df.duplicated().sum())

Duplicados restantes: 0

In [9]:
# Recriando a amostra de filmes completos apos o tratamento dos registros duplicados, garantindo que a nova base tb
# nao tenha duplicatas.

df_filmes_completos = df.dropna(subset=['budget', 'revenue', 'runtime']).copy()

In [10]:
print(df.dtypes)

adult                       str
budget                  float64
genres                      str
id                          str
original_language           str
original_title              str
popularity              float64
production_companies        str
production_countries        str
release_date                str
revenue                 float64
runtime                 float64
spoken_languages            str
status                      str
title                       str
video                    object
vote_average            float64
vote_count              float64
dtype: object

In [ ]:
# Verificando se ainda existem registros duplicados.
print("Duplicados:", df.duplicated().sum())

# Verificando os tipos finais das colunas.
print("\nTipos de dados:")
print(df.dtypes)

# Verificando valores ausentes 
print("\nValores ausentes:")
print(df.isnull().sum())

Duplicados: 0

Tipos de dados:
adult                       str
budget                  float64
genres                      str
id                          str
original_language           str
original_title              str
popularity              float64
production_companies        str
production_countries        str
release_date                str
revenue                 float64
runtime                 float64
spoken_languages            str
status                      str
title                       str
video                    object
vote_average            float64
vote_count              float64
dtype: object

Valores ausentes:
adult                       0
budget                  36554
genres                      0
id                          0
original_language          11
original_title              0
popularity                  0
production_companies        0
production_countries        0
release_date               84
revenue                 38038
runtime                  1815
spoken_languages            0
status                     81
title                       0
video                       0
vote_average                0
vote_count                  0
dtype: int64

In [ ]:
# A coluna release_date representa datas, mas foi carregada como texto.

df['release_date'] = pd.to_datetime(df['release_date'],errors='coerce')

print(df['release_date'].dtype)

print("Datas ausentes:", df['release_date'].isnull().sum())

datetime64[us]
Datas ausentes: 84

In [ ]:
# Criando novamente a amostra após finalizar o pre-processamento
# da base geral.

df_filmes_completos = df.dropna(subset=['budget', 'revenue', 'runtime']).copy()

In [ ]:
# Calculando as medidas de centralização do orçamento dos filmes.
# .mean,median,mode -> função que calcula a média, mediana e moda da lib pandas

media_budget = df_filmes_completos['budget'].mean()
mediana_budget = df_filmes_completos['budget'].median()
moda_budget = df_filmes_completos['budget'].mode()

print(f"Média do orçamento: ${media_budget:,.2f}")
print(f"Mediana do orçamento: ${mediana_budget:,.2f}")
print("Moda do orçamento:")
print(moda_budget)

Média do orçamento: $31,155,319.02
Mediana do orçamento: $17,000,000.00
Moda do orçamento:
0    20000000.0
Name: budget, dtype: float64

In [15]:
# Calculando as medidas de centralização da receita dos filmes.

media_revenue = df_filmes_completos['revenue'].mean()
mediana_revenue = df_filmes_completos['revenue'].median()
moda_revenue = df_filmes_completos['revenue'].mode()

print(f"Média da receita: ${media_revenue:,.2f}")
print(f"Mediana da receita: ${mediana_revenue:,.2f}")
print("Moda da receita:")
print(moda_revenue)

Média da receita: $90,511,534.04
Mediana da receita: $30,000,000.00
Moda da receita:
0    12000000.0
Name: revenue, dtype: float64

In [ ]:
# Calculando os quartis do orçamento dos filmes.
# quantile -> função que calcula os quartis da lib pandas

q1_budget = df_filmes_completos['budget'].quantile(0.25)
q2_budget = df_filmes_completos['budget'].quantile(0.50)
q3_budget = df_filmes_completos['budget'].quantile(0.75)

print(f"Q1 (25%): ${q1_budget:,.2f}")
print(f"Q2 (50%): ${q2_budget:,.2f}")
print(f"Q3 (75%): ${q3_budget:,.2f}")

Q1 (25%): $5,200,000.00
Q2 (50%): $17,000,000.00
Q3 (75%): $40,000,000.00

In [17]:
# Calculando os quartis da receita dos filmes.

q1_revenue = df_filmes_completos['revenue'].quantile(0.25)
q2_revenue = df_filmes_completos['revenue'].quantile(0.50)
q3_revenue = df_filmes_completos['revenue'].quantile(0.75)

print(f"Q1 (25%): ${q1_revenue:,.2f}")
print(f"Q2 (50%): ${q2_revenue:,.2f}")
print(f"Q3 (75%): ${q3_revenue:,.2f}")

Q1 (25%): $7,070,330.00
Q2 (50%): $30,000,000.00
Q3 (75%): $100,000,000.00

In [18]:
# Calculando a amplitude dos orçamentos.


menor_budget = df_filmes_completos['budget'].min()
maior_budget = df_filmes_completos['budget'].max()
amplitude_budget = maior_budget - menor_budget

print(f"Menor orçamento: ${menor_budget:,.2f}")
print(f"Maior orçamento: ${maior_budget:,.2f}")
print(f"Amplitude: ${amplitude_budget:,.2f}")

Menor orçamento: $1.00
Maior orçamento: $380,000,000.00
Amplitude: $379,999,999.00

### Caso curioso
O filme com o menor budget foi 1 dolar?

In [19]:
# Verificando os menores orçamentos registrados na amostra
# para identificar possíveis valores atípicos ou inconsistentes.

df_filmes_completos[['title', 'budget', 'revenue']].sort_values('budget').head(20)

                           title  budget     revenue
38526                      Saamy     1.0         3.0
19258    Love, Wedding, Marriage     1.0      1378.0
22278             Aquí Entre Nos     1.0   2755584.0
4000              Less Than Zero     1.0  12396383.0
922                 East of Eden     1.0         5.0
2483                Lost & Found     1.0       100.0
15873                  Tere Naam     1.0         2.0
35086                The Letters     1.0         1.0
3342                Modern Times     1.0   8500000.0
180                 Mute Witness     2.0         1.0
16909                        Boy     3.0        43.0
12183      No Mercy for the Rude     3.0         4.0
29548         Falling From Grace     3.0       232.0
43649                   Desmundo     3.0         3.0
15074         A Farewell to Arms     4.0        25.0
949           A Farewell to Arms     4.0        25.0
1150      Madonna: Truth or Dare     4.0        29.0
5248   Every Which Way But Loose     5.0        85.0
37250             Raja Natwarlal     5.0         4.0
39716         The Cherry Orchard     5.0       135.0

In [20]:
# Calculando a amplitude das receitas.

menor_revenue = df_filmes_completos['revenue'].min()
maior_revenue = df_filmes_completos['revenue'].max()
amplitude_revenue = maior_revenue - menor_revenue

print(f"Menor receita: ${menor_revenue:,.2f}")
print(f"Maior receita: ${maior_revenue:,.2f}")
print(f"Amplitude: ${amplitude_revenue:,.2f}")

Menor receita: $1.00
Maior receita: $2,787,965,087.00
Amplitude: $2,787,965,086.00

In [21]:
# Calculando o desvio padrão dos orçamentos.
# std = standart desviation -> função que calcula o desvio padrão da lib pandas

desvio_budget = df_filmes_completos['budget'].std()

print(f"Desvio padrão do orçamento: ${desvio_budget:,.2f}")

Desvio padrão do orçamento: $40,186,809.67

In [22]:
# Calculando a variância dos orçamentos.
# A variância mede a dispersão dos valores em relação à média.

variancia_budget = df_filmes_completos['budget'].var()

print(f"Variância do orçamento: {variancia_budget:,.2f}")

Variância do orçamento: 1,614,979,671,145,484.25